site_name: FPGA Workflow Documentation
site_url: https://fpga-workflow-research.readthedocs.io

nav: 
    - Home: index.md
    - Getting Started: techInfo.md
    - Developing Custom Applications: customApps.md
    - Modifying Apps for F1: modApps.md
    - Testing Log: testLog.md 

theme: readthedocs
repo_url: https://github.com/Galactius/fpga-workflow-research
edit_uri: blob/main/docs/

