site_name: FPGA Workflow Documentation
site_url: https://fpga-workflow-research.readthedocs.io

nav: 
    - Home: index.md
    - About: docs.md 

theme: readthedocs
repo_url: https://github.com/Galactius/fpga-workflow-research
edit_uri: blob/master/docs/

